<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        //Usuarios
        DB::table('seg_usuarios')->insert(['usu_id' => 1,'usu_nombres' => "Wesner",'usu_apellidos' => "Ché",'usu_correo' => "wesner@home.com.gt",'usu_cui' => "2304229340101",'usu_clave' => Hash::make('Unlimited009'), 'usu_telefono' => "", 'usu_admin'=>true]);
        DB::table('seg_usuarios')->insert(['usu_id' => 2,'usu_nombres' => "Marcos",'usu_apellidos' => "Jimenez",'usu_correo' => "mjimenez@home.com.gt",'usu_cui' => "2731465130101",'usu_clave' => Hash::make('123456789'),  'usu_telefono' => "",'usu_admin'=>true]);
        DB::table('seg_usuarios')->insert(['usu_id' => 3,'usu_nombres' => "Nelson",'usu_apellidos' => "Donis",'usu_correo' => "ndonis@home.com.gt",'usu_cui' => "2533576830101",'usu_clave' => Hash::make('123456789'),  'usu_telefono' => "",'usu_admin'=>true]);


        //Paises
        DB::table('cat_pais')->insert(['pais_id'=>1, 'pais_codigo'=>'GT', 'pais_nombre'=>'Guatemala']);

        //Departamentos
        DB::table('cat_departamento')->insert(['dep_id'=>1, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Alta Verapaz']);
        DB::table('cat_departamento')->insert(['dep_id'=>2, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Baja Verapaz']);
        DB::table('cat_departamento')->insert(['dep_id'=>3, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Chimaltenango']);
        DB::table('cat_departamento')->insert(['dep_id'=>4, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Chiquimula']);
        DB::table('cat_departamento')->insert(['dep_id'=>5, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Petén']);
        DB::table('cat_departamento')->insert(['dep_id'=>6, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'El Progreso']);
        DB::table('cat_departamento')->insert(['dep_id'=>7, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Quiché']);
        DB::table('cat_departamento')->insert(['dep_id'=>8, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Escuintla']);
        DB::table('cat_departamento')->insert(['dep_id'=>9, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Guatemala']);
        DB::table('cat_departamento')->insert(['dep_id'=>10, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Huehuetenango']);
        DB::table('cat_departamento')->insert(['dep_id'=>11, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Izabal']);
        DB::table('cat_departamento')->insert(['dep_id'=>12, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Jalapa']);
        DB::table('cat_departamento')->insert(['dep_id'=>13, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Jutiapa']);
        DB::table('cat_departamento')->insert(['dep_id'=>14, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Quetzaltenango']);
        DB::table('cat_departamento')->insert(['dep_id'=>15, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Retalhuleu']);
        DB::table('cat_departamento')->insert(['dep_id'=>16, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Sacatepéquez']);
        DB::table('cat_departamento')->insert(['dep_id'=>17, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'San Marcos']);
        DB::table('cat_departamento')->insert(['dep_id'=>18, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Santa Rosa']);
        DB::table('cat_departamento')->insert(['dep_id'=>19, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Sololá']);
        DB::table('cat_departamento')->insert(['dep_id'=>20, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Suchitepéquez']);
        DB::table('cat_departamento')->insert(['dep_id'=>21, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Totonicapán']);
        DB::table('cat_departamento')->insert(['dep_id'=>22, 'dep_pais_fk'=>1, 'dep_codigo'=>'', 'dep_nombre'=>'Zacapa']);

        //municipios
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chahal', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chisec', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cobán', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Fray Bartolomé de las Casas', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Tinta', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Lanquín', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Panzós', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Raxruhá', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Cristóbal Verapaz', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Chamelco', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Carchá', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz Verapaz', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa María Cahabón', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Senahú', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tamahú', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tactic', 'mun_estado'=>1, 'mun_dep_fk'=>1]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tucurú', 'mun_estado'=>1, 'mun_dep_fk'=>1]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cubulco', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Granados', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Purulhá', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Rabinal', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Salamá', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Jerónimo', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Chicaj', 'mun_estado'=>1, 'mun_dep_fk'=>2]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz el Chol', 'mun_estado'=>1, 'mun_dep_fk'=>2]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Acatenango', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chimaltenango', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Tejar', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Parramos', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Patzicía', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Patzún', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pochuta', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés Itzapa', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José Poaquíl', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Comalapa', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Martín Jilotepeque', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Apolonia', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz Balanyá', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tecpán', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Yepocapa', 'mun_estado'=>1, 'mun_dep_fk'=>3]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zaragoza', 'mun_estado'=>1, 'mun_dep_fk'=>3]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Camotán', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chiquimula', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Concepción Las Minas', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Esquipulas', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ipala', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jocotán', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Olopa', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Quezaltepeque', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Jacinto', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José la Arada', 'mun_estado'=>1, 'mun_dep_fk'=>4]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Ermita', 'mun_estado'=>1, 'mun_dep_fk'=>4]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Dolores', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Chal', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ciudad Flores', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Libertad', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Las Cruces', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Melchor de Mencos', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Poptún', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Benito', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Francisco', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Luis', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Ana', 'mun_estado'=>1, 'mun_dep_fk'=>5]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sayaxché', 'mun_estado'=>1, 'mun_dep_fk'=>5]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Jícaro', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Guastatoya', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Morazán', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Agustín Acasaguastlán', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio La Paz', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Cristóbal Acasaguastlán', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sanarate', 'mun_estado'=>1, 'mun_dep_fk'=>6]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sansare', 'mun_estado'=>1, 'mun_dep_fk'=>6]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Canillá', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chajul', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chicamán', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chiché', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chichicastenango', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chinique', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cunén', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ixcán Playa Grande', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Joyabaj', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nebaj', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pachalum', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Patzité', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sacapulas', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés Sajcabajá', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Ilotenango', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Bartolomé Jocotenango', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Cotzal', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Jocopilas', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz del Quiché', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Uspantán', 'mun_estado'=>1, 'mun_dep_fk'=>7]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zacualpa', 'mun_estado'=>1, 'mun_dep_fk'=>7]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Escuintla', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Guanagazapa', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Iztapa', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Democracia', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Gomera', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Masagua', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nueva Concepción', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Palín', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Vicente Pacaya', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Lucía Cotzumalguapa', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Siquinalá', 'mun_estado'=>1, 'mun_dep_fk'=>8]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tiquisate', 'mun_estado'=>1, 'mun_dep_fk'=>8]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Amatitlán', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chinautla', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chuarrancho', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Guatemala', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Fraijanes', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Mixco', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Palencia', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José del Golfo', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José Pinula', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Petapa', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Ayampuc', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Raymundo', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Catarina Pinula', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Villa Canales', 'mun_estado'=>1, 'mun_dep_fk'=>9]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Villa Nueva', 'mun_estado'=>1, 'mun_dep_fk'=>9]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Aguacatán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chiantla', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Colotenango', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Concepción Huista', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cuilco', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Huehuetenango', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jacaltenango', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Democracia', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Libertad', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Malacatancito', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nentón', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Huista', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Gaspar Ixchil', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Ildefonso Ixtahuacán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Atitán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Ixcoy', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Mateo Ixtatán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Acatán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Nécta', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Soloma', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Rafael La Independencia', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Rafael Pétzal', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Sebastián Coatán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Sebastián Huehuetenango', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Ana Huista', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Bárbara', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz Barillas', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Eulalia', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santiago Chimaltenango', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tectitán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Todos Santos Cuchumatán', 'mun_estado'=>1, 'mun_dep_fk'=>10]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Unión Cantinil', 'mun_estado'=>1, 'mun_dep_fk'=>10]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Estor', 'mun_estado'=>1, 'mun_dep_fk'=>11]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Livingston', 'mun_estado'=>1, 'mun_dep_fk'=>11]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Los Amates', 'mun_estado'=>1, 'mun_dep_fk'=>11]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Morales', 'mun_estado'=>1, 'mun_dep_fk'=>11]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Puerto Barrios', 'mun_estado'=>1, 'mun_dep_fk'=>11]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jalapa', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Mataquescuintla', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Monjas', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Carlos Alzatate', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Luis Jilotepeque', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Manuel Chaparrón', 'mun_estado'=>1, 'mun_dep_fk'=>12]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Pinula', 'mun_estado'=>1, 'mun_dep_fk'=>12]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Agua Blanca', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Asunción Mita', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Atescatempa', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Comapa', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Conguaco', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Adelanto', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Progreso', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jalpatagua', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jerez', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jutiapa', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Moyuta', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pasaco', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Quesada', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José Acatempa', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Catarina Mita', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Yupiltepeque', 'mun_estado'=>1, 'mun_dep_fk'=>13]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zapotitlán', 'mun_estado'=>1, 'mun_dep_fk'=>13]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Almolonga', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cabricán', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cajolá', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cantel', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Coatepeque', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Colomba Costa Cuca', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Concepción Chiquirichapa', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Palmar', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Flores Costa Cuca', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Génova', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Huitán', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Esperanza', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Olintepeque', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Palestina de Los Altos', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Quetzaltenango', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Salcajá', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Carlos Sija', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Francisco La Unión', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Ostuncalco', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Martín Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Mateo', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Sigüilá', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sibilia', 'mun_estado'=>1, 'mun_dep_fk'=>14]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zunil', 'mun_estado'=>1, 'mun_dep_fk'=>14]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Champerico', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Asintal', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nuevo San Carlos', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Retalhuleu', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés Villa Seca', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Felipe Reu', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Martín Zapotitlán', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Sebastián', 'mun_estado'=>1, 'mun_dep_fk'=>15]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz Muluá', 'mun_estado'=>1, 'mun_dep_fk'=>15]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Alotenango', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ciudad Vieja', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Jocotenango', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Antigua Guatemala', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Magdalena Milpas Altas', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pastores', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Aguas Calientes', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Bartolomé Milpas Altas', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Lucas Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Dueñas', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Catarina Barahona', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Lucía Milpas Altas', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa María de Jesús', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santiago Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santo Domingo Xenacoj', 'mun_estado'=>1, 'mun_dep_fk'=>16]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sumpango', 'mun_estado'=>1, 'mun_dep_fk'=>16]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ayutla', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Catarina', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Comitancillo', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Concepción Tutuapa', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Quetzal', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'El Tumbador', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Esquipulas Palo Gordo', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ixchiguán', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Blanca', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Reforma', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Malacatán', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nuevo Progreso', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Ocós', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pajapita', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Río Blanco', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Cristóbal Cucho', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José El Rodeo', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José Ojetenam', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Lorenzo', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Marcos', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Ixtahuacán', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pablo', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro Sacatepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Rafael Pie de la Cuesta', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sibinal', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sipacapa', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tacaná', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tajumulco', 'mun_estado'=>1, 'mun_dep_fk'=>17]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Tejutla', 'mun_estado'=>1, 'mun_dep_fk'=>17]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Barberena', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Casillas', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chiquimulilla', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cuilapa', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Guazacapán', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nueva Santa Rosa', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Oratorio', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pueblo Nuevo Viñas', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Tecuaco', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Rafael las Flores', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz Naranjo', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa María Ixhuatán', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Rosa de Lima', 'mun_estado'=>1, 'mun_dep_fk'=>18]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Taxisco', 'mun_estado'=>1, 'mun_dep_fk'=>18]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Concepción', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Nahualá', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Panajachel', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés Semetabaj', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Palopó', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José Chacayá', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Lucas Tolimán', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Marcos La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pablo La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pedro La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Catarina Ixtahuacán', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Catarina Palopó', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Clara La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Cruz La Laguna', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Lucía Utatlán', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa María Visitación', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santiago Atitlán', 'mun_estado'=>1, 'mun_dep_fk'=>19]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Sololá', 'mun_estado'=>1, 'mun_dep_fk'=>19]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Chicacao', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cuyotenango', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Mazatenango', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Patulul', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Pueblo Nuevo', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Río Bravo', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Samayac', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Antonio Suchitepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Bernardino', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Francisco Zapotitlán', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Gabriel', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José El Idolo', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San José La Maquina', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Juan Bautista', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Lorenzo', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Miguel Panán', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Pablo Jocopilas', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Bárbara', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santo Domingo Suchitepéquez', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santo Tomás La Unión', 'mun_estado'=>1, 'mun_dep_fk'=>20]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zunilito', 'mun_estado'=>1, 'mun_dep_fk'=>20]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Momostenango', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Andrés Xecul', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Bartolo', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Cristóbal Totonicapán', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Francisco El Alto', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa Lucía La Reforma', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Santa María Chiquimula', 'mun_estado'=>1, 'mun_dep_fk'=>21]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Totonicapán', 'mun_estado'=>1, 'mun_dep_fk'=>21]);

        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Cabañas', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Estanzuela', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Gualán', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Huité', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'La Unión', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Río Hondo', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Diego', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'San Jorge', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Teculután', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Usumatlán', 'mun_estado'=>1, 'mun_dep_fk'=>22]);
        DB::table('cat_municipio')->insert(['mun_nombre'=> 'Zacapa', 'mun_estado'=>1, 'mun_dep_fk'=>22]);


        //Categorias
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Accesorios']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Accesorios para mujer']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Accesorios para hombre']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Alimentos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Alimentos artesanales']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Almientos especiales']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Bebidas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Café']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ingredientes']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Repostería']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Utencilios de cocina']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Alta costura']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Artesanías']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Arte']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Manualidades varias']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Artículos de Limpieza']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Artículos para el hogar']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Asesoría de imagen']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Automotriz']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Belleza']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Cuidado de la piel']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Gimnasio']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Maquillaje']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Nutricionista']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Productos para el Cabello']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Salon de belleza']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Spa']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Uñas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Bordados']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Caligrafía / Lettering']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Computación']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Software']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Corte y confección']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Coworking / Oficina virtual']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Cursos de idiomas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Deporte']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Diseño y Publicidad']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Articulos Promocionales']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Community Management']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Diseño Gráfico']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Diseño Industrial']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Diseño web']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Edición de video']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ilustración']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Mercadeo']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Mercadeo digital']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Educación']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Clases particulares']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Guardería / DayCare']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Electrónica']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Reparaciones']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Embarazo']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Empaque']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Estilista']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Eventos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Catering']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Entretemiento']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Fotográfos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Piñatas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Planificadores de Eventos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ferreteria']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Fumigadores']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Hogar']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Arquitectura']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Cocinas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Decoradores de Interiores']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Muebles']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Rotulación']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Jardinería y Floristería']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Arreglos florales']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Paisajismo']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Viveros']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Joyas y Accesorios']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Maquinaria']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Oficios de mantenimiento e instalación']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Carpiteria']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Cerrajero']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Electircistas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Plomeria']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Papelería']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Invitaciones']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Productos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Productos de Electrónica']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Productos varios']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Red de empresarios Indigenas']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Accesorios REI']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Madera']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Miniaturas REI']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Tejido típico']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ropa']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ropa de hombre']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ropa de mujer']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ropa deportiva']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Ropa para bebes']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Salud']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Servicio de limpieza']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Servicios de Seguridad']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Servicios profesionales y asesorías']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Abogados']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Consultorías']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Contabilidad']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Psicologos']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Trámites']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Tienda en linea']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Transporte  mensajería y envios']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Entrega de paquetes']);
        DB::table('cat_categoria')->insert(['cat_nombre'=>'Mensajería']);
    }
}
